### ISSUE TITLE
[New Protocol]: Push Protocol

### ISSUE THREAD

**Issue by SovaSniper** [solide-project/solide-dapp#3]
### Description

Push Protocol, (*formerly known as EPNS*), serves as a revolutionary web3 communication network that facilitates cross-chain notifications and messaging for decentralized applications (dApps), wallets, and various services across Ethereum, BNB Chain, and Polygon. Functioning as the world's first blockchain-agnostic decentralized communication protocol for Web3, Push enables the validation and indexing of diverse communications, including notifications and chats. Push aims to address a crucial gap in web3 infrastructure by establishing a communication layer. This layer allows any smart contract, dApp, or backend service to integrate Push, offering real-time communications tied directly to users' wallet addresses. These off-chain, gasless communications enhance the everyday experience for blockchain users, providing encrypted and secure notifications that are easily integrable by any web3 application or wallet, ultimately creating a more user-friendly and familiar experience akin to web2.
### Information

```json
{
    "github": "https://github.com/ethereum-push-notification-service",
    "website": "https://push.org",
    "blog": "https://push.org/blog",
    "documentation": "https://push.org/docs",
    "discord": "https://discord.com/invite/pushprotocol",
    "twitter": "https://twitter.com/pushprotocol",
}
```

### Usefulness for Solide and the community

The Push protocol is an innovative system, catering to Ethereum and introduces cross-chain notifications and messaging for decentralized applications, smart contracts, and backend services. By establishing a communication layer, Push Protocol enables real-time communications directly tied to users' wallet addresses, offering off-chain, gasless, and encrypted notifications which are new concepts within the contracts hub Solide collects. It also demonstrates the ability to showcase smart contracts and implementation for off-chain, gasless, and encrypted communications provided by Push Protocol to enhance the user experience, making it more user-friendly and familiar like a web2 solution. So a very useful way to understand the communication layers within the blockchain.

### Contracts that can be integrated into Solide

- Main Protocol Contracts: [push-smart-contracts](https://github.com/ethereum-push-notification-service/push-smart-contracts)
- Push Token Contracts: [push-smart-contracts-genesis](https://github.com/ethereum-push-notification-service/push-smart-contracts-genesis)

### Does the contract provide audit?

Yes, audit reports are available at [Push Audit Doc](https://push.org/docs/notifications/push-smart-contracts/security-audits)

**Comment by 5208980** [comment]
Archive
