### ISSUE TITLE
[New Protocol]: Fuse Network

### ISSUE THREAD

**Issue by SovaSniper** [solide-project/solide-dapp#4]
### Description

Fuse Network, established in 2019, is a pioneering force in the Web3 landscape, offering an enterprise-grade, reliable, and secure decentralized EVM-compatible public blockchain. Fuse is positioned as a game-changer for entrepreneurs and organizations looking to experiment, launch, and scale Web3 apps. The platform's value proposition lies in its robust infrastructure, complemented by a native marketplace for decentralized services run by the community. Fuse simplifies Web3 integration through its mobile-first SDK, making it an attractive choice for businesses seeking to bring their Web3 ideas to life effortlessly. The network offers a comprehensive toolkit for project teams and startups to build and scale decentralized applications on an EVM-compatible blockchain.
### Information

```json
{
    "github": "https://github.com/fuseio",
    "website": "https://www.fuse.io",
    "blog": "https://news.fuse.io",
    "documentation": "https://docs.fuse.io",
    "discord": "https://discord.com/invite/jpPMeSZ",
    "twitter": "https://twitter.com/Fuse_network",
}
```

### Usefulness for Solide and the community

FuseBox is a valuable addition to Solide as it simplifies blockchain development on the Fuse Network. It provides developers with tools like a Bundler and Paymaster, enabling a seamless Gasless experience. This integration enhances Solide's capabilities, offering users the ability to explore and experiment with smart contracts on the Fuse Network easily. Fuse is designed to be friendly for blockchain & non-blockchain developers alike, the same value as Solide.
### Contracts that can be integrated into Solide

List the contracts that can be integrated into Solide. If there are no contracts, please remove this section.

- Fuse Network Contracts: [Fuse Network Contract](https://github.com/fuseio/fuse-network)
- Fuse Studio Contracts: [Fuse Studio Contract](https://github.com/gmx-io/gmx-contracts/tree/master/contracts)
- Official smart contracted deployed on Fuse: [Fuse Bridge/Token Contracts](https://docs.fuse.io/docs/developers/important-smart-contracts/major-deployed-contracts#core)

### Does the contract provided audit?

Yes, audit reports are available at [Fuse Network Contract Audits](https://github.com/fuseio/fuse-network/tree/master/audits).

**Comment by 5208980** [comment]
Please label this issue as **enchantment**
